import './globals.css'
import { Inter } from 'next/font/google'
import Wallet from "../components/Wallet"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Template for Mina protocol Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>{children}</body>
    </html>
  )
}
